package org.redrune.utility.constants;

/**
 * @author Tyluur <itstyluur@icloud.com>
 * @since 9/8/2017
 */
public interface PacketConstants {
	
	byte[] PACKET_SIZES = new byte[256];
	
	int ACTION_BUTTON1_PACKET = 61;
	
	int ACTION_BUTTON2_PACKET = 64;
	
	int ACTION_BUTTON3_PACKET = 4;
	
	int ACTION_BUTTON4_PACKET = 52;
	
	int ACTION_BUTTON5_PACKET = 81;
	
	int ACTION_BUTTON6_PACKET = 18;
	
	int ACTION_BUTTON7_PACKET = 10;
	
	int ACTION_BUTTON8_PACKET = 25;
	
	int ACTION_BUTTON9_PACKET = 91;
	
	int ACTION_BUTTON10_PACKET = 20;
	
	int RECEIVE_PACKET_COUNT_PACKET = 15;
	
	int ACCEPT_TRADE_CHAT_PACKET = 46;
	
	int PLAYER_TRADE_OPTION_PACKET = 77;
	
	int WALKING_PACKET = 12;
	
	int MINI_WALKING_PACKET = 83;
	
	int MAGIC_ON_ITEM_PACKET = -1;
	
	int MOVE_CAMERA_PACKET = 5;
	
	int INTERFACE_ON_GROUND_ITEM_PACKET = -1;
	
	int CLICK_PACKET = 84;
	
	int MOVE_MOUSE_PACKET = 29;
	
	int KEY_TYPED_PACKET = 68;
	
	int CLOSE_INTERFACE_PACKET = 56;
	
	int COMMANDS_PACKET = 70;
	
	int ITEM_ON_ITEM_PACKET = 73;
	
	int IN_OUT_SCREEN_PACKET = 75;
	
	int SWITCH_DETAIL = 4;
	
	int DONE_LOADING_REGION = 33;
	
	int PING_PACKET = 16;
	
	int PING_STATISTICS_PACKET = 85;
	
	int SCREEN_PACKET = 87;
	
	int CHAT_TYPE_PACKET = 23;
	
	int CHAT_PACKET = 36;
	
	int PUBLIC_QUICK_CHAT_PACKET = 30;
	
	int ADD_FRIEND_PACKET = 51;
	
	int JOIN_FRIEND_CHAT_PACKET = 1;
	
	int CHANGE_FRIEND_CHAT_PACKET = 41;
	
	int KICK_FRIEND_CHAT_PACKET = 32;
	
	int REMOVE_FRIEND_PACKET = 8;
	
	int SEND_FRIEND_MESSAGE_PACKET = 72;
	
	int SEND_FRIEND_QUICK_CHAT_PACKET = 79;
	
	int OBJECT_CLICK1_PACKET = 11;
	
	int OBJECT_CLICK2_PACKET = 2;
	
	int OBJECT_CLICK3_PACKET = 76;
	
	int OBJECT_EXAMINE_PACKET = 47;
	
	int NPC_CLICK1_PACKET = 9;
	
	int NPC_CLICK2_PACKET = 31;
	
	int NPC_CLICK3_PACKET = 67;
	
	int NPC_CLICK4_PACKET = 28;
	
	int ATTACK_NPC = 66;
	
	int REPORT_ABUSE_PACKET = 11;
	
	int PLAYER_OPTION_1_PACKET = 14;
	
	int PLAYER_OPTION_2_PACKET = 53;
	
	int ITEM_TAKE_PACKET = 24;

	int ITEM_ON_FLOOR_PACKET = 86;

	int DIALOGUE_CONTINUE_PACKET = 54;
	
	int ENTER_INTEGER_PACKET = 3;
	
	int ENTER_STRING_PACKET = 59;
	
	int SWITCH_INTERFACE_ITEM_PACKET = 26;
	
	int INTERFACE_ON_PLAYER = 40;
	
	int INTERFACE_ON_NPC = 65;
	
	int ITEM_ON_OBJECT_PACKET = 42;
	
	int NPC_EXAMINE_PACKET = 92;
	
	int ITEM_EXAMINE_PACKET = 27;
	
	int COLOR_ID_PACKET = 22;
	
	int ENTER_LONG_STRING_PACKET = 7;
	
	int CLAN_FORUM_THREAD_PACKET = 74;
	
	int WORLD_LIST_REQUEST_PACKET = 34;
	
	int WINDOW_SWITCH_PACKET = 93;

	int GRAND_EXCHANGE_SELECTION = 13;
	
	static void loadPacketSizes() {
		for (int id = 0; id < 256; id++) {
			PACKET_SIZES[id] = -4;
		}
		PACKET_SIZES[64] = 8;
		PACKET_SIZES[18] = 8;
		PACKET_SIZES[25] = 8;
		PACKET_SIZES[41] = -1;
		PACKET_SIZES[14] = 3;
		PACKET_SIZES[46] = 3;
		PACKET_SIZES[87] = 6;
		PACKET_SIZES[47] = 7;
		PACKET_SIZES[57] = 3;
		PACKET_SIZES[67] = 3;
		PACKET_SIZES[91] = 8;
		PACKET_SIZES[24] = 7;
		PACKET_SIZES[73] = 16;
		PACKET_SIZES[40] = 11;
		PACKET_SIZES[36] = -1;
		PACKET_SIZES[74] = -1;
		PACKET_SIZES[31] = 3;
		PACKET_SIZES[54] = 6;
		PACKET_SIZES[12] = 5;
		PACKET_SIZES[23] = 1;
		PACKET_SIZES[9] = 3;
		PACKET_SIZES[17] = -1;
		PACKET_SIZES[44] = -1;
		PACKET_SIZES[88] = -1;
		PACKET_SIZES[42] = 15;
		PACKET_SIZES[49] = 3;
		PACKET_SIZES[21] = 15;
		PACKET_SIZES[59] = -1;
		PACKET_SIZES[37] = -1;
		PACKET_SIZES[6] = 8;
		PACKET_SIZES[55] = 7;
		PACKET_SIZES[69] = 9;
		PACKET_SIZES[26] = 16;
		PACKET_SIZES[39] = 12;
		PACKET_SIZES[71] = 4;
		PACKET_SIZES[22] = 2;
		PACKET_SIZES[32] = -1;
		PACKET_SIZES[79] = -1;
		PACKET_SIZES[89] = 4;
		PACKET_SIZES[90] = -1;
		PACKET_SIZES[15] = 4;
		PACKET_SIZES[72] = -2;
		PACKET_SIZES[20] = 8;
		PACKET_SIZES[92] = 3;
		PACKET_SIZES[82] = 3;
		PACKET_SIZES[28] = 3;
		PACKET_SIZES[81] = 8;
		PACKET_SIZES[7] = -1;
		PACKET_SIZES[4] = 8;
		PACKET_SIZES[60] = -1;
		PACKET_SIZES[13] = 2;
		PACKET_SIZES[52] = 8;
		PACKET_SIZES[65] = 11;
		PACKET_SIZES[85] = 2;
		PACKET_SIZES[86] = 7;
		PACKET_SIZES[78] = -1;
		PACKET_SIZES[83] = 18;
		PACKET_SIZES[27] = 7;
		PACKET_SIZES[2] = 7;
		PACKET_SIZES[93] = 1;
		PACKET_SIZES[70] = -1;
		PACKET_SIZES[1] = -1;
		PACKET_SIZES[8] = -1;
		PACKET_SIZES[11] = 7;
		PACKET_SIZES[0] = 9;
		PACKET_SIZES[51] = -1;
		PACKET_SIZES[5] = 4;
		PACKET_SIZES[45] = 7;
		PACKET_SIZES[75] = 4;
		PACKET_SIZES[53] = 3;
		PACKET_SIZES[33] = 0;
		PACKET_SIZES[50] = 3;
		PACKET_SIZES[76] = 7;
		PACKET_SIZES[80] = -1;
		PACKET_SIZES[77] = 3;
		PACKET_SIZES[68] = -1;
		PACKET_SIZES[43] = 3;
		PACKET_SIZES[30] = -1;
		PACKET_SIZES[19] = 3;
		PACKET_SIZES[16] = 0;
		PACKET_SIZES[34] = 4;
		PACKET_SIZES[48] = 0;
		PACKET_SIZES[56] = 0;
		PACKET_SIZES[58] = 2;
		PACKET_SIZES[10] = 8;
		PACKET_SIZES[35] = 7;
		PACKET_SIZES[84] = 6;
		PACKET_SIZES[66] = 3;
		PACKET_SIZES[61] = 8;
		PACKET_SIZES[29] = -1;
		PACKET_SIZES[62] = 3;
		PACKET_SIZES[3] = 4;
		PACKET_SIZES[63] = 4;
		PACKET_SIZES[73] = 16;
		PACKET_SIZES[38] = -1;
	}
}
