/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.redrune.gui.shop;

import org.redrune.cache.Cache;
import org.redrune.game.content.entity.actor.player.market.Shop;
import org.redrune.game.content.entity.actor.player.market.ShopRepository;
import org.redrune.game.entity.item.Item;
import org.redrune.utility.constants.GameConstants;

import javax.activation.ActivationDataFlavor;
import javax.activation.DataHandler;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.dnd.DragSource;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.List;
import java.util.*;
import java.util.Map.Entry;

/**
 * @author Tyluur
 */
public class ShopEditor extends JFrame {

    /**
     * The map of local shops loaded - this will be modified by user activity on the gui
     */
    private final Map<Integer, Shop> localShops = new HashMap<>();

    // variables used for the gui
    private JPanel configurationPanel;

    private JLabel currencyNameLabel;

    private JTextField currencyNameTextField;

    private JLabel identifierLabel;

    private JTextField identifierTextField;

    private JTable itemTable;

    private JScrollPane listScrollPane;

    private JButton saveButton;

    private JRadioButton sellBackButton;

    private JList<String> shopList;

    private JLabel shopNameLabel;

    private JTextField shopNameTextField;

    private JScrollPane tableScrollPane;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        listScrollPane = new JScrollPane();
        shopList = new JList<>();
        tableScrollPane = new JScrollPane();
        itemTable = new JTable();
        configurationPanel = new JPanel();
        shopNameLabel = new JLabel();
        identifierLabel = new JLabel();
        identifierTextField = new JTextField();
        shopNameTextField = new JTextField();
        currencyNameLabel = new JLabel();
        currencyNameTextField = new JTextField();
        saveButton = new JButton();
        sellBackButton = new JRadioButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        refreshListing();
        listScrollPane.setViewportView(shopList);
        shopList.addListSelectionListener(this::shopListActionPerformed);
        shopList.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (!SwingUtilities.isRightMouseButton(e)) {
                    return;
                }
                JPopupMenu popupMenu = new JPopupMenu();
                JMenuItem addMenuItem = new JMenuItem("Add");
                JMenuItem deleteMenuItem = new JMenuItem("Delete");
                addMenuItem.addActionListener(this::addMenuItemActionHandler);
                deleteMenuItem.addActionListener(ae -> {
                    int index = shopList.locationToIndex(e.getPoint());
                    Shop shop = getShopByIndex(index);
                    if (shop == null) {
                        throw new IllegalStateException("Unable to delete shop - could not find shop by index " + index);
                    }
                    localShops.remove(shop.getIdentifier());
                    refreshListing();
                });
                int preferredHeight = shopList.getPreferredSize().height;
                int mouseHeight = e.getPoint().y;
                if (mouseHeight > preferredHeight) {
                    popupMenu.add(addMenuItem);
                } else if (!shopList.isSelectionEmpty() && shopList.locationToIndex(e.getPoint()) == shopList.getSelectedIndex()) {
                    popupMenu.add(deleteMenuItem);
                }
                popupMenu.show(shopList, e.getX(), e.getY());
            }

            private void addMenuItemActionHandler(ActionEvent evt) {
                String shopName = JOptionPane.showInputDialog("Enter the name of the new shop:");
                Shop shop = new Shop(localShops.size() + 1, shopName, Collections.EMPTY_LIST, "null");
                localShops.put(shop.getIdentifier(), shop);
                refreshListing();
            }
        });

        itemTable.setModel(new DefaultTableModel(new Object[][]{{null, null, null, null}, {null, null, null, null}, {null, null, null, null}, {null, null, null, null}}, new String[]{}));
        itemTable.getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        itemTable.setTransferHandler(new TableRowTransferHandler());
        itemTable.setDropMode(DropMode.INSERT_ROWS);
        itemTable.setDragEnabled(true);
        itemTable.setFillsViewportHeight(true);
        //table.setAutoCreateRowSorter(true); //XXX
        itemTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (!SwingUtilities.isRightMouseButton(e)) {
                    return;
                }
                System.out.println("Right clicked");
                JPopupMenu popupMenu = new JPopupMenu();
                JMenuItem addMenuItem = new JMenuItem("Add");
                JMenuItem deleteMenuItem = new JMenuItem("Delete");
                popupMenu.add(addMenuItem);
                popupMenu.add(deleteMenuItem);

                addMenuItem.addActionListener(ae -> {
                    int itemId = -1;
                    int itemAmount = -1;
                    try {
                        itemId = Integer.parseInt(JOptionPane.showInputDialog("Enter item id:"));
                        itemAmount = Integer.parseInt(JOptionPane.showInputDialog("Enter item amount:"));
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Invalid input!");
                    }
                    if (itemId == -1 || itemAmount == -1) {
                        return;
                    }
                    Shop shop = getSelectedShop();
                    if (shop == null) {
                        throw new IllegalStateException("Unable to identify selected shop");
                    }
                    shop.getItems().add(new Item(itemId, itemAmount));
                    updateTable(shopList.getSelectedIndex());
                });
                deleteMenuItem.addActionListener(al -> {
                    int row = itemTable.rowAtPoint(e.getPoint());
                    int column = itemTable.columnAtPoint(e.getPoint());
                    Shop shop = getSelectedShop();
                    if (shop == null) {
                        throw new IllegalStateException("Unable to identify selected shop.");
                    }
                    Item item = shop.getItems().get(row);
                    if (!itemTable.isRowSelected(row)) {
                        itemTable.changeSelection(row, column, false, false);
                    }
                    shop.getItems().remove(item);
                    updateTable(shopList.getSelectedIndex());
                });
                popupMenu.show(itemTable, e.getX(), e.getY());
            }
        });
        tableScrollPane.setViewportView(itemTable);

        configurationPanel.setBorder(BorderFactory.createTitledBorder("Configuration"));

        shopNameLabel.setText("Shop Name");
        shopNameTextField.addActionListener(this::shopNameTextFieldActionPerformed);

        identifierLabel.setText("Identifier");
        identifierTextField.setEditable(false);
        identifierTextField.addActionListener(this::identifierTextFieldActionPerformed);

        currencyNameLabel.setText("Currency Name");

        saveButton.setText("Save");
        saveButton.addActionListener(this::saveButtonActionPerformed);
        currencyNameTextField.addActionListener(this::currencyTextFieldActionPerformed);

        sellBackButton.setText("Sell Back Allowed");
        sellBackButton.addActionListener(this::sellBackButtonActionPerformed);

        setTitle(GameConstants.SERVER_NAME + " Shop Editor");

        javax.swing.GroupLayout configurationPanelLayout = new javax.swing.GroupLayout(configurationPanel);
        configurationPanel.setLayout(configurationPanelLayout);
        configurationPanelLayout.setHorizontalGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(configurationPanelLayout.createSequentialGroup().addContainerGap().addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(shopNameLabel).addComponent(identifierLabel)).addGap(18, 18, 18).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(identifierTextField).addComponent(shopNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addComponent(currencyNameLabel).addGap(18, 18, 18).addComponent(currencyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(35, 35, 35)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addComponent(sellBackButton).addGap(158, 158, 158)))).addGroup(configurationPanelLayout.createSequentialGroup().addGap(232, 232, 232).addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)));
        configurationPanelLayout.setVerticalGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addGap(19, 19, 19).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(currencyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(identifierLabel).addComponent(identifierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(currencyNameLabel))).addGap(18, 18, 18).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(shopNameLabel).addComponent(shopNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(sellBackButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE).addComponent(saveButton)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, 0).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE).addComponent(configurationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(listScrollPane).addGroup(layout.createSequentialGroup().addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(configurationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
        setLocationRelativeTo(null);

    }

    private void shopListActionPerformed(ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            return;
        }
        if (shopList.getSelectedIndex() == -1) {
            return;
        }
        updateTable(shopList.getSelectedIndex());
    }

    /**
     * This method refreshes the shops shown on the {@link #shopList}
     */
    private void refreshListing() {
        shopList.setModel(new AbstractListModel<String>() {

            @Override
            public int getSize() {
                return localShops.size();
            }

            @Override
            public String getElementAt(int index) {
                Shop shop = getShopByIndex(index);
                if (shop == null) {
                    System.out.println("Unable to find shop by index " + index);
                    return "N/A";
                }
                return shop.getName();
            }
        });
    }

    /**
     * When an action is performed in the {@link #identifierTextField}, necessary handling is done here
     */
    private void identifierTextFieldActionPerformed(ActionEvent evt) {
        System.out.println("evt = [" + evt + "]");
    }

    /**
     * This method handles actions performed in the shop name text field
     */
    private void shopNameTextFieldActionPerformed(ActionEvent evt) {
        Shop shop = getSelectedShop();
        if (shop == null) {
            throw new IllegalStateException("Unable to handle a shop event for a shop that wasn't selected");
        }
        String newName = evt.getActionCommand();
        if (newName.equals(shop.getName())) {
            return;
        }
        shop.setName(newName);
        refreshListing();
    }

    /**
     * This method handles actions performed in the currency name text field
     */
    private void currencyTextFieldActionPerformed(ActionEvent evt) {
        Shop shop = getSelectedShop();
        if (shop == null) {
            throw new IllegalStateException("Unable to handle a shop event for a shop that wasn't selected");
        }
        String newName = evt.getActionCommand();
        if (newName.equals(shop.getName())) {
            return;
        }
        shop.setCurrencyName(newName);
    }

    /**
     * When the save button invokes and event, it is handled here
     */
    private void saveButtonActionPerformed(ActionEvent evt) {
        java.util.List<Shop> shops = new ArrayList<>(localShops.values());
        ShopRepository.saveShops(shops);
    }

    /**
     * Whenh an action is performed on the {@link #sellBackButton}, necessary handling is done here
     */
    private void sellBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Shop shop = getSelectedShop();
        if (shop == null) {
            throw new IllegalStateException("Unable to change shop state for a shop that isn't selected");
        }
        shop.setGeneralStore(sellBackButton.isSelected());
    }

    /**
     * If there is a shop that is selected in the list, this method will return it
     */
    private Shop getSelectedShop() {
        return getShopByIndex(shopList.getSelectedIndex());
    }

    /**
     * Gets a shop by the index, this does not use the identifier value in the map, rather the order in which shops are
     * stored in the file.
     */
    private Shop getShopByIndex(int index) {
        int count = 0;
        for (Entry<Integer, Shop> entry : localShops.entrySet()) {
            if (count == index) {
                return entry.getValue();
            }
            count++;
        }
        return null;
    }

    private void updateTableItemsAfterInsertion() {
        Shop shop = getSelectedShop();
        if (shop == null) {
            throw new IllegalStateException("Unable to update shop - unidentified shop.");
        }
        List<Item> items = new LinkedList<>();
        for (int count = 0; count < itemTable.getRowCount(); count++) {
            String name = itemTable.getValueAt(count, 0).toString();
            String itemId = itemTable.getValueAt(count, 1).toString();
            String itemAmount = itemTable.getValueAt(count, 2).toString();
            items.add(new Item(Integer.parseInt(itemId), Integer.parseInt(itemAmount)));
        }
        shop.getItems().clear();
        shop.getItems().addAll(items);
        updateTable(shopList.getSelectedIndex());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String... args) {
        try {
            Cache.initialize();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            EventQueue.invokeLater(() -> {
                ShopEditor editor = new ShopEditor();
                editor.initializeRequirements();
                editor.setVisible(true);
            });
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException | IOException e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    /**
     * Sll the requirements for this gui to load are initialized in this method
     */
    private void initializeRequirements() {
        ShopRepository.registerAll();
        localShops.putAll(ShopRepository.getShops());
        initComponents();
    }

    /**
     * The items table is updated for the shop at the selected index
     */
    protected void updateTable(int index) {
        final Shop shop = getShopByIndex(index);
        if (shop == null) {
            throw new IllegalStateException("Unable to find shop by index " + index);
        }
        System.out.println("To update shop: " + shop.getName());
        DefaultTableModel model = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };
        model.addColumn("Name");
        model.addColumn("Id");
        model.addColumn("Amount");
        if (shop.getItems() != null) {
            for (Item item : shop.getItems()) {
                if (item == null) {
                    continue;
                }
                model.addRow(new Object[]{item.getDefinitions().getName(), item.getDefinitions().getId(), item.getAmount()});
            }
        }
        identifierTextField.setText(String.valueOf(shop.getIdentifier()));
        shopNameTextField.setText(shop.getName());
        shopNameTextField.setToolTipText(shop.getName());
        currencyNameTextField.setText(shop.getCurrencyName());
        currencyNameTextField.setToolTipText(shop.getCurrencyName());
        sellBackButton.setSelected(shop.isGeneralStore());
        itemTable.setModel(model);
        setTableModelListener();
        itemTable.scrollRectToVisible(itemTable.getCellRect(itemTable.getRowCount() - 1, itemTable.getColumnCount(), true));
    }

    /**
     * When events are fired on the table this method is invoked
     */
    private void setTableModelListener() {
        itemTable.getModel().addTableModelListener(e -> {
            if (e.getType() != TableModelEvent.UPDATE) {
                return;
            }
            int selectedIndex = shopList.getSelectedIndex();
            Shop shop = getShopByIndex(selectedIndex);
            if (shop == null) {
                throw new IllegalStateException("Unable to access shop with index " + selectedIndex);
            }
            Item item = shop.getItems().get(e.getFirstRow());
            if (e.getColumn() == 1) {
                item.setId((short) Integer.parseInt((String) itemTable.getModel().getValueAt(e.getFirstRow(), e.getColumn())));
            } else {
                item.setAmount(Integer.parseInt((String) itemTable.getModel().getValueAt(e.getFirstRow(), e.getColumn())));
            }
            System.out.println("Item [" + item + "] updated");
        });
    }

    class TableRowTransferHandler extends TransferHandler {

        private final DataFlavor localObjectFlavor;

        private int[] indices;

        private int addIndex = -1; //Location where items were added

        private int addCount; //Number of items added.

        protected TableRowTransferHandler() {
            super();
            localObjectFlavor = new ActivationDataFlavor(Object[].class, DataFlavor.javaJVMLocalObjectMimeType, "Array of items");
        }

        @Override
        protected Transferable createTransferable(JComponent c) {
            JTable table = (JTable) c;
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            java.util.List<Object> list = new ArrayList<>();
            indices = table.getSelectedRows();
            for (int i : indices) {
                list.add(model.getDataVector().get(i));
            }
            Object[] transferedObjects = list.toArray();
            return new DataHandler(transferedObjects, localObjectFlavor.getMimeType());
        }

        @Override
        public boolean canImport(TransferHandler.TransferSupport info) {
            JTable table = (JTable) info.getComponent();
            boolean isDropable = info.isDrop() && info.isDataFlavorSupported(localObjectFlavor);
            table.setCursor(isDropable ? DragSource.DefaultMoveDrop : DragSource.DefaultMoveNoDrop);
            return isDropable;
        }

        @Override
        public int getSourceActions(JComponent c) {
            return TransferHandler.MOVE;
        }

        @Override
        public boolean importData(TransferHandler.TransferSupport info) {
            if (!canImport(info)) {
                return false;
            }
            TransferHandler.DropLocation tdl = info.getDropLocation();
            if (!(tdl instanceof JTable.DropLocation)) {
                return false;
            }
            JTable.DropLocation dl = (JTable.DropLocation) tdl;
            JTable target = (JTable) info.getComponent();
            DefaultTableModel model = (DefaultTableModel) target.getModel();
            int index = dl.getRow();
            int max = model.getRowCount();
            if (index < 0 || index > max) {
                index = max;
            }
            addIndex = index;
            target.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            try {
                Object[] values = (Object[]) info.getTransferable().getTransferData(localObjectFlavor);
                addCount = values.length;
                for (int i = 0; i < values.length; i++) {
                    int idx = index++;
                    model.insertRow(idx, (Vector) values[i]);
                    target.getSelectionModel().addSelectionInterval(idx, idx);
                }
                return true;
            } catch (UnsupportedFlavorException | IOException ex) {
                ex.printStackTrace();
            }
            return false;
        }

        @Override
        protected void exportDone(JComponent c, Transferable data, int action) {
            cleanup(c, action == TransferHandler.MOVE);
        }

        //If the remove argument is true, the drop has been
        //successful and it's time to remove the selected items
        //from the list. If the remove argument is false, it
        //was a Copy operation and the original list is left
        //intact.
        protected void cleanup(JComponent c, boolean remove) {
            if (remove && indices != null) {
                c.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                DefaultTableModel model = (DefaultTableModel) ((JTable) c).getModel();
                //If we are moving items around in the same list, we
                //need to adjust the indices accordingly, since those
                //after the insertion point have moved.
                if (addCount > 0) {
                    for (int i = 0; i < indices.length; i++) {
                        if (indices[i] >= addIndex) {
                            indices[i] += addCount;
                        }
                    }
                }
                for (int i = indices.length - 1; i >= 0; i--) {
                    model.removeRow(indices[i]);
                }
            }
            indices = null;
            addCount = 0;
            addIndex = -1;
            updateTableItemsAfterInsertion();
        }
    }
}
