/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.redrune.gui.shop

import org.redrune.cache.Cache
import org.redrune.game.content.entity.actor.player.market.Shop
import org.redrune.game.content.entity.actor.player.market.ShopRepository.registerAll
import org.redrune.game.content.entity.actor.player.market.ShopRepository.saveShops
import org.redrune.game.content.entity.actor.player.market.ShopRepository.shops
import org.redrune.game.entity.item.Item
import org.redrune.utility.constants.GameConstants
import java.awt.Cursor
import java.awt.EventQueue
import java.awt.datatransfer.DataFlavor
import java.awt.datatransfer.Transferable
import java.awt.datatransfer.UnsupportedFlavorException
import java.awt.dnd.DragSource
import java.awt.event.ActionEvent
import java.awt.event.ActionListener
import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.io.IOException
import java.util.*
import javax.activation.ActivationDataFlavor
import javax.activation.DataHandler
import javax.swing.*
import javax.swing.event.ListSelectionEvent
import javax.swing.event.ListSelectionListener
import javax.swing.event.TableModelEvent
import javax.swing.event.TableModelListener
import javax.swing.table.DefaultTableModel

/**
 * @author Tyluur
 */
class ShopEditor : JFrame() {
    /**
     * The map of local shops loaded - this will be modified by user activity on the gui
     */
    private val localShops: MutableMap<Int, Shop> = HashMap()

    // variables used for the gui
    private var configurationPanel: JPanel? = null
    private var currencyNameLabel: JLabel? = null
    private var currencyNameTextField: JTextField? = null
    private var identifierLabel: JLabel? = null
    private var identifierTextField: JTextField? = null
    private var itemTable: JTable? = null
    private var listScrollPane: JScrollPane? = null
    private var saveButton: JButton? = null
    private var sellBackButton: JRadioButton? = null
    private var shopList: JList<String>? = null
    private var shopNameLabel: JLabel? = null
    private var shopNameTextField: JTextField? = null
    private var tableScrollPane: JScrollPane? = null

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private fun initComponents() {
        listScrollPane = JScrollPane()
        shopList = JList()
        tableScrollPane = JScrollPane()
        itemTable = JTable()
        configurationPanel = JPanel()
        shopNameLabel = JLabel()
        identifierLabel = JLabel()
        identifierTextField = JTextField()
        shopNameTextField = JTextField()
        currencyNameLabel = JLabel()
        currencyNameTextField = JTextField()
        saveButton = JButton()
        sellBackButton = JRadioButton()
        defaultCloseOperation = EXIT_ON_CLOSE
        refreshListing()
        listScrollPane!!.setViewportView(shopList)
        shopList!!.addListSelectionListener(ListSelectionListener { evt: ListSelectionEvent ->
            shopListActionPerformed(
                evt
            )
        })
        shopList!!.addMouseListener(object : MouseAdapter() {
            override fun mousePressed(e: MouseEvent) {
                if (!SwingUtilities.isRightMouseButton(e)) {
                    return
                }
                val popupMenu = JPopupMenu()
                val addMenuItem = JMenuItem("Add")
                val deleteMenuItem = JMenuItem("Delete")
                addMenuItem.addActionListener(ActionListener { evt: ActionEvent -> addMenuItemActionHandler(evt) })
                deleteMenuItem.addActionListener(ActionListener { ae: ActionEvent? ->
                    val index = shopList!!.locationToIndex(e.point)
                    val shop = getShopByIndex(index)
                        ?: throw IllegalStateException("Unable to delete shop - could not find shop by index $index")
                    localShops.remove(shop.identifier)
                    refreshListing()
                })
                val preferredHeight = shopList!!.preferredSize.height
                val mouseHeight = e.point.y
                if (mouseHeight > preferredHeight) {
                    popupMenu.add(addMenuItem)
                } else if (!shopList!!.isSelectionEmpty && shopList!!.locationToIndex(e.point) == shopList!!.selectedIndex) {
                    popupMenu.add(deleteMenuItem)
                }
                popupMenu.show(shopList, e.x, e.y)
            }

            private fun addMenuItemActionHandler(evt: ActionEvent) {
                val shopName = JOptionPane.showInputDialog("Enter the name of the new shop:")
                val shop = Shop(localShops.size + 1, shopName, listOf(), "null")
                localShops[shop.identifier] = shop
                refreshListing()
            }
        })
        itemTable!!.model = DefaultTableModel(
            arrayOf(
                arrayOf(null, null, null, null),
                arrayOf(null, null, null, null),
                arrayOf(null, null, null, null),
                arrayOf(null, null, null, null)
            ), arrayOf<String>()
        )
        itemTable!!.selectionModel.selectionMode = ListSelectionModel.MULTIPLE_INTERVAL_SELECTION
        itemTable!!.transferHandler = TableRowTransferHandler()
        itemTable!!.dropMode = DropMode.INSERT_ROWS
        itemTable!!.dragEnabled = true
        itemTable!!.fillsViewportHeight = true
        //table.setAutoCreateRowSorter(true); //XXX
        itemTable!!.addMouseListener(object : MouseAdapter() {
            override fun mousePressed(e: MouseEvent) {
                if (!SwingUtilities.isRightMouseButton(e)) {
                    return
                }
                println("Right clicked")
                val popupMenu = JPopupMenu()
                val addMenuItem = JMenuItem("Add")
                val deleteMenuItem = JMenuItem("Delete")
                popupMenu.add(addMenuItem)
                popupMenu.add(deleteMenuItem)
                addMenuItem.addActionListener(ActionListener {
                    var itemId = -1
                    var itemAmount = -1
                    try {
                        itemId = JOptionPane.showInputDialog("Enter item id:").toInt()
                        itemAmount = JOptionPane.showInputDialog("Enter item amount:").toInt()
                    } catch (ex: Exception) {
                        JOptionPane.showMessageDialog(null, "Invalid input!")
                    }
                    if (itemId == -1 || itemAmount == -1) {
                        return@ActionListener
                    }
                    val shop: Shop = selectedShop ?: throw IllegalStateException("Unable to identify selected shop")
                    shop.items.add(Item(itemId, itemAmount))
                    updateTable(shopList!!.selectedIndex)
                })
                deleteMenuItem.addActionListener(ActionListener { al: ActionEvent? ->
                    val row = itemTable!!.rowAtPoint(e.point)
                    val column = itemTable!!.columnAtPoint(e.point)
                    val shop: Shop = selectedShop ?: throw IllegalStateException("Unable to identify selected shop.")
                    val item = shop.items[row]
                    if (!itemTable!!.isRowSelected(row)) {
                        itemTable!!.changeSelection(row, column, false, false)
                    }
                    shop.items.remove(item)
                    updateTable(shopList!!.selectedIndex)
                })
                popupMenu.show(itemTable, e.x, e.y)
            }
        })
        tableScrollPane!!.setViewportView(itemTable)
        configurationPanel!!.border = BorderFactory.createTitledBorder("Configuration")
        shopNameLabel!!.text = "Shop Name"
        shopNameTextField!!.addActionListener(ActionListener { evt: ActionEvent -> shopNameTextFieldActionPerformed(evt) })
        identifierLabel!!.text = "Identifier"
        identifierTextField!!.isEditable = false
        identifierTextField!!.addActionListener(ActionListener { evt: ActionEvent ->
            identifierTextFieldActionPerformed(
                evt
            )
        })
        currencyNameLabel!!.text = "Currency Name"
        saveButton!!.text = "Save"
        saveButton!!.addActionListener(ActionListener { evt: ActionEvent -> saveButtonActionPerformed(evt) })
        currencyNameTextField!!.addActionListener(ActionListener { evt: ActionEvent ->
            currencyTextFieldActionPerformed(
                evt
            )
        })
        sellBackButton!!.text = "Sell Back Allowed"
        sellBackButton!!.addActionListener(ActionListener { evt: ActionEvent -> sellBackButtonActionPerformed(evt) })
        title = GameConstants.SERVER_NAME + " Shop Editor"
        val configurationPanelLayout = GroupLayout(configurationPanel)
        configurationPanel!!.layout = configurationPanelLayout
        configurationPanelLayout.setHorizontalGroup(
            configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                configurationPanelLayout.createSequentialGroup().addContainerGap().addGroup(
                    configurationPanelLayout.createParallelGroup(
                        GroupLayout.Alignment.LEADING
                    ).addComponent(shopNameLabel).addComponent(identifierLabel)
                ).addGap(18, 18, 18).addGroup(
                    configurationPanelLayout.createParallelGroup(
                        GroupLayout.Alignment.LEADING, false
                    ).addComponent(identifierTextField)
                        .addComponent(shopNameTextField, GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE.toInt())
                ).addPreferredGap(
                    LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE.toInt()
                ).addGroup(
                    configurationPanelLayout.createParallelGroup(
                        GroupLayout.Alignment.LEADING
                    ).addGroup(
                        GroupLayout.Alignment.TRAILING,
                        configurationPanelLayout.createSequentialGroup().addComponent(currencyNameLabel)
                            .addGap(18, 18, 18).addComponent(
                                currencyNameTextField,
                                GroupLayout.PREFERRED_SIZE,
                                127,
                                GroupLayout.PREFERRED_SIZE
                            ).addGap(35, 35, 35)
                    ).addGroup(
                        GroupLayout.Alignment.TRAILING,
                        configurationPanelLayout.createSequentialGroup().addComponent(sellBackButton)
                            .addGap(158, 158, 158)
                    )
                )
            ).addGroup(
                configurationPanelLayout.createSequentialGroup().addGap(232, 232, 232)
                    .addComponent(saveButton, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE.toInt())
            )
        )
        configurationPanelLayout.setVerticalGroup(
            configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                GroupLayout.Alignment.TRAILING,
                configurationPanelLayout.createSequentialGroup().addGap(19, 19, 19).addGroup(
                    configurationPanelLayout.createParallelGroup(
                        GroupLayout.Alignment.LEADING
                    ).addComponent(currencyNameTextField, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                        .addGroup(
                            configurationPanelLayout.createParallelGroup(
                                GroupLayout.Alignment.BASELINE
                            ).addComponent(identifierLabel).addComponent(
                                identifierTextField,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE
                            ).addComponent(currencyNameLabel)
                        )
                ).addGap(18, 18, 18).addGroup(
                    configurationPanelLayout.createParallelGroup(
                        GroupLayout.Alignment.LEADING
                    ).addGroup(
                        configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(shopNameLabel).addComponent(
                                shopNameTextField,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE
                            )
                    ).addComponent(sellBackButton)
                ).addPreferredGap(
                    LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE.toInt()
                ).addComponent(saveButton)
            )
        )
        val layout = GroupLayout(contentPane)
        contentPane.layout = layout
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup()
                    .addComponent(listScrollPane, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0).addGroup(
                        layout.createParallelGroup(
                            GroupLayout.Alignment.LEADING, false
                        ).addComponent(tableScrollPane, GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE.toInt())
                            .addComponent(
                                configurationPanel,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE.toInt()
                            )
                    )
            )
        )
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(listScrollPane).addGroup(
                layout.createSequentialGroup()
                    .addComponent(tableScrollPane, GroupLayout.PREFERRED_SIZE, 383, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        LayoutStyle.ComponentPlacement.RELATED
                    ).addComponent(
                        configurationPanel,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE.toInt()
                    )
            )
        )
        pack()
        setLocationRelativeTo(null)
    }

    private fun shopListActionPerformed(evt: ListSelectionEvent) {
        if (!evt.valueIsAdjusting) {
            return
        }
        if (shopList!!.selectedIndex == -1) {
            return
        }
        updateTable(shopList!!.selectedIndex)
    }

    /**
     * This method refreshes the shops shown on the [.shopList]
     */
    private fun refreshListing() {
        shopList!!.model = object : AbstractListModel<String?>() {
            override fun getSize(): Int {
                return localShops.size
            }

            override fun getElementAt(index: Int): String {
                val shop = getShopByIndex(index)
                if (shop == null) {
                    println("Unable to find shop by index $index")
                    return "N/A"
                }
                return shop.name
            }
        }
    }

    /**
     * When an action is performed in the [.identifierTextField], necessary handling is done here
     */
    private fun identifierTextFieldActionPerformed(evt: ActionEvent) {
        println("evt = [$evt]")
    }

    /**
     * This method handles actions performed in the shop name text field
     */
    private fun shopNameTextFieldActionPerformed(evt: ActionEvent) {
        val shop = selectedShop
            ?: throw IllegalStateException("Unable to handle a shop event for a shop that wasn't selected")
        val newName = evt.actionCommand
        if (newName == shop.name) {
            return
        }
        shop.name = newName
        refreshListing()
    }

    /**
     * This method handles actions performed in the currency name text field
     */
    private fun currencyTextFieldActionPerformed(evt: ActionEvent) {
        val shop = selectedShop
            ?: throw IllegalStateException("Unable to handle a shop event for a shop that wasn't selected")
        val newName = evt.actionCommand
        if (newName == shop.name) {
            return
        }
        shop.currencyName = newName
    }

    /**
     * When the save button invokes and event, it is handled here
     */
    private fun saveButtonActionPerformed(evt: ActionEvent) {
        val shops: List<Shop> = ArrayList(localShops.values)
        saveShops(shops)
    }

    /**
     * Whenh an action is performed on the [.sellBackButton], necessary handling is done here
     */
    private fun sellBackButtonActionPerformed(evt: ActionEvent) {
        val shop = selectedShop
            ?: throw IllegalStateException("Unable to change shop state for a shop that isn't selected")
        shop.isGeneralStore = sellBackButton!!.isSelected
    }

    private val selectedShop: Shop?
        /**
         * If there is a shop that is selected in the list, this method will return it
         */
        private get() = getShopByIndex(shopList!!.selectedIndex)

    /**
     * Gets a shop by the index, this does not use the identifier value in the map, rather the order in which shops are
     * stored in the file.
     */
    private fun getShopByIndex(index: Int): Shop? {
        var count = 0
        for ((_, value) in localShops) {
            if (count == index) {
                return value
            }
            count++
        }
        return null
    }

    private fun updateTableItemsAfterInsertion() {
        val shop = selectedShop ?: throw IllegalStateException("Unable to update shop - unidentified shop.")
        val items: MutableList<Item> = LinkedList()
        for (count in 0 until itemTable!!.rowCount) {
            val name = itemTable!!.getValueAt(count, 0).toString()
            val itemId = itemTable!!.getValueAt(count, 1).toString()
            val itemAmount = itemTable!!.getValueAt(count, 2).toString()
            items.add(Item(itemId.toInt(), itemAmount.toInt()))
        }
        shop.items.clear()
        shop.items.addAll(items)
        updateTable(shopList!!.selectedIndex)
    }

    /**
     * Sll the requirements for this gui to load are initialized in this method
     */
    private fun initializeRequirements() {
        registerAll()
        localShops.putAll(shops)
        initComponents()
    }

    /**
     * The items table is updated for the shop at the selected index
     */
    protected fun updateTable(index: Int) {
        val shop = getShopByIndex(index) ?: throw IllegalStateException("Unable to find shop by index $index")
        println("To update shop: " + shop.name)
        val model: DefaultTableModel = object : DefaultTableModel() {
            override fun isCellEditable(row: Int, column: Int): Boolean {
                return column != 0
            }
        }
        model.addColumn("Name")
        model.addColumn("Id")
        model.addColumn("Amount")
        if (shop.items != null) {
            for (item in shop.items) {
                if (item == null) {
                    continue
                }
                model.addRow(arrayOf<Any>(item.definitions.name, item.definitions.id, item.amount))
            }
        }
        identifierTextField!!.text = shop.identifier.toString()
        shopNameTextField!!.text = shop.name
        shopNameTextField!!.toolTipText = shop.name
        currencyNameTextField!!.text = shop.currencyName
        currencyNameTextField!!.toolTipText = shop.currencyName
        sellBackButton!!.isSelected = shop.isGeneralStore
        itemTable!!.model = model
        setTableModelListener()
        itemTable!!.scrollRectToVisible(
            itemTable!!.getCellRect(
                itemTable!!.rowCount - 1,
                itemTable!!.columnCount,
                true
            )
        )
    }

    /**
     * When events are fired on the table this method is invoked
     */
    private fun setTableModelListener() {
        itemTable!!.model.addTableModelListener(TableModelListener { e: TableModelEvent ->
            if (e.type != TableModelEvent.UPDATE) {
                return@TableModelListener
            }
            val selectedIndex = shopList!!.selectedIndex
            val shop = getShopByIndex(selectedIndex)
                ?: throw IllegalStateException("Unable to access shop with index $selectedIndex")
            val item = shop.items[e.firstRow]
            if (e.column == 1) {
                item.id = (itemTable!!.model.getValueAt(e.firstRow, e.column) as String).toInt()
                    .toShort().toInt()
            } else {
                item.amount = (itemTable!!.model.getValueAt(e.firstRow, e.column) as String).toInt()
            }
            println("Item [$item] updated")
        })
    }

    internal inner class TableRowTransferHandler : TransferHandler() {
        private val localObjectFlavor: DataFlavor
        private var indices: IntArray? = null
        private var addIndex = -1 //Location where items were added
        private var addCount = 0 //Number of items added.

        init {
            localObjectFlavor =
                ActivationDataFlavor(Array<Any>::class.java, DataFlavor.javaJVMLocalObjectMimeType, "Array of items")
        }

        override fun createTransferable(c: JComponent): Transferable {
            val table = c as JTable
            val model = table.model as DefaultTableModel
            val list: MutableList<Any> = ArrayList()
            indices = table.selectedRows
            if (indices != null) {
                for (i in indices!!) {
                    list.add(model.dataVector[i])
                }
            }
            val transferedObjects = list.toTypedArray()
            return DataHandler(transferedObjects, localObjectFlavor.mimeType)
        }

        override fun canImport(info: TransferSupport): Boolean {
            val table = info.component as JTable
            val isDropable = info.isDrop && info.isDataFlavorSupported(localObjectFlavor)
            table.cursor = if (isDropable) DragSource.DefaultMoveDrop else DragSource.DefaultMoveNoDrop
            return isDropable
        }

        override fun getSourceActions(c: JComponent): Int {
            return MOVE
        }

        override fun importData(info: TransferSupport): Boolean {
            if (!canImport(info)) {
                return false
            }
            val tdl = info.dropLocation as? JTable.DropLocation ?: return false
            val target = info.component as JTable
            val model = target.model as DefaultTableModel
            var index = tdl.row
            val max = model.rowCount
            if (index < 0 || index > max) {
                index = max
            }
            addIndex = index
            target.cursor = Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)
            try {
                val values = info.transferable.getTransferData(localObjectFlavor) as Array<Any>
                addCount = values.size
                for (i in values.indices) {
                    val idx = index++
                    model.insertRow(idx, values[i] as Vector<*>)
                    target.selectionModel.addSelectionInterval(idx, idx)
                }
                return true
            } catch (ex: UnsupportedFlavorException) {
                ex.printStackTrace()
            } catch (ex: IOException) {
                ex.printStackTrace()
            }
            return false
        }

        override fun exportDone(c: JComponent, data: Transferable, action: Int) {
            cleanup(c, action == MOVE)
        }

        //If the remove argument is true, the drop has been
        //successful and it's time to remove the selected items
        //from the list. If the remove argument is false, it
        //was a Copy operation and the original list is left
        //intact.
        protected fun cleanup(c: JComponent, remove: Boolean) {
            if (remove && indices != null) {
                c.cursor = Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)
                val model = (c as JTable).model as DefaultTableModel
                //If we are moving items around in the same list, we
                //need to adjust the indices accordingly, since those
                //after the insertion point have moved.
                if (addCount > 0) {
                    for (i in indices!!.indices) {
                        if (indices!![i] >= addIndex) {
                            indices!![i] += addCount
                        }
                    }
                }
                for (i in indices!!.indices.reversed()) {
                    model.removeRow(indices!![i])
                }
            }
            indices = null
            addCount = 0
            addIndex = -1
            updateTableItemsAfterInsertion()
        }
    }

    companion object {
        /**
         * @param args
         * the command line arguments
         */
        @JvmStatic
        fun main(args: Array<String>) {
            try {
                Cache.initialize()
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
                EventQueue.invokeLater(Runnable {
                    val editor = ShopEditor()
                    editor.initializeRequirements()
                    editor.isVisible = true
                })
            } catch (e: ClassNotFoundException) {
                e.printStackTrace()
                System.exit(1)
            } catch (e: InstantiationException) {
                e.printStackTrace()
                System.exit(1)
            } catch (e: IllegalAccessException) {
                e.printStackTrace()
                System.exit(1)
            } catch (e: UnsupportedLookAndFeelException) {
                e.printStackTrace()
                System.exit(1)
            } catch (e: IOException) {
                e.printStackTrace()
                System.exit(1)
            }
        }
    }
}