/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.redrune.gui;

import javax.swing.*;

/**
 * @author Tyluur
 */
public class ShopEditor extends javax.swing.JFrame {
	
	/**
	 * Creates new form ShopEditor
	 */
	public ShopEditor() {
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		
		listScrollPane = new javax.swing.JScrollPane();
		shopList = new javax.swing.JList<>();
		tableScrollPane = new javax.swing.JScrollPane();
		itemTable = new javax.swing.JTable();
		configurationPanel = new javax.swing.JPanel();
		shopNameLabel = new javax.swing.JLabel();
		identifierLabel = new javax.swing.JLabel();
		identifierTextField = new javax.swing.JTextField();
		shopNameTextField = new javax.swing.JTextField();
		currencyNameLabel = new javax.swing.JLabel();
		currencyNameTextField = new javax.swing.JTextField();
		saveButton = new javax.swing.JButton();
		sellBackButton = new javax.swing.JRadioButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		shopList.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
			
			public int getSize() {
				return strings.length;
			}
			
			public String getElementAt(int i) {
				return strings[i];
			}
		});
		listScrollPane.setViewportView(shopList);
		
		itemTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null }, { null, null, null, null } }, new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		tableScrollPane.setViewportView(itemTable);
		
		configurationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuration"));
		
		shopNameLabel.setText("Shop Name");
		
		identifierLabel.setText("Identifier");
		
		identifierTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				identifierTextFieldActionPerformed(evt);
			}
		});
		
		currencyNameLabel.setText("Currency Name");
		
		saveButton.setText("Save");
		
		sellBackButton.setText("Sell Back Allowed");
		sellBackButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sellBackButtonActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout configurationPanelLayout = new javax.swing.GroupLayout(configurationPanel);
		configurationPanel.setLayout(configurationPanelLayout);
		configurationPanelLayout.setHorizontalGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(configurationPanelLayout.createSequentialGroup().addContainerGap().addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(shopNameLabel).addComponent(identifierLabel)).addGap(18, 18, 18).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(identifierTextField).addComponent(shopNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addComponent(currencyNameLabel).addGap(18, 18, 18).addComponent(currencyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(35, 35, 35)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addComponent(sellBackButton).addGap(166, 166, 166)))).addGroup(configurationPanelLayout.createSequentialGroup().addGap(246, 246, 246).addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		configurationPanelLayout.setVerticalGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addGap(19, 19, 19).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(identifierLabel).addComponent(identifierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(currencyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(currencyNameLabel)).addGap(18, 18, 18).addGroup(configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(shopNameLabel).addComponent(shopNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(sellBackButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(saveButton).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, 0).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE).addComponent(configurationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(listScrollPane).addGroup(layout.createSequentialGroup().addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(configurationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		
		pack();
	}// </editor-fold>
	
	private void identifierTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	
	private void sellBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}
	
	/**
	 * @param args
	 * 		the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		//</editor-fold>
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ShopEditor().setVisible(true);
			}
		});
	}
	
	// Variables declaration - do not modify
	private javax.swing.JPanel configurationPanel;
	
	private javax.swing.JLabel currencyNameLabel;
	
	private javax.swing.JTextField currencyNameTextField;
	
	private javax.swing.JLabel identifierLabel;
	
	private javax.swing.JTextField identifierTextField;
	
	private javax.swing.JTable itemTable;
	
	private javax.swing.JScrollPane listScrollPane;
	
	private javax.swing.JButton saveButton;
	
	private javax.swing.JRadioButton sellBackButton;
	
	private javax.swing.JList<String> shopList;
	
	private javax.swing.JLabel shopNameLabel;
	
	private javax.swing.JTextField shopNameTextField;
	
	private javax.swing.JScrollPane tableScrollPane;
	// End of variables declaration
}
