/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.redrune.gui;

import org.redrune.game.content.entity.actor.player.market.Shop;
import org.redrune.game.content.entity.actor.player.market.ShopRepository;
import org.redrune.game.entity.item.Item;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

/**
 * @author Tyluur
 */
public class ShopEditor extends JFrame {
	
	/**
	 * The map of local shops loaded - this will be modified by user activity on the gui
	 */
	private final Map<Integer, Shop> localShops = new HashMap<>();
	
	// variables used for the gui
	private JPanel configurationPanel;
	
	private JLabel currencyNameLabel;
	
	private JTextField currencyNameTextField;
	
	private JLabel identifierLabel;
	
	private JTextField identifierTextField;
	
	private JTable itemTable;
	
	private JScrollPane listScrollPane;
	
	private JButton saveButton;
	
	private JRadioButton sellBackButton;
	
	private JList<String> shopList;
	
	private JLabel shopNameLabel;
	
	private JTextField shopNameTextField;
	
	private JScrollPane tableScrollPane;
	
	/**
	 * Creates new form ShopEditor
	 */
	public ShopEditor() {
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		
		listScrollPane = new JScrollPane();
		shopList = new JList<>();
		tableScrollPane = new JScrollPane();
		itemTable = new JTable();
		configurationPanel = new JPanel();
		shopNameLabel = new JLabel();
		identifierLabel = new JLabel();
		identifierTextField = new JTextField();
		shopNameTextField = new JTextField();
		currencyNameLabel = new JLabel();
		currencyNameTextField = new JTextField();
		saveButton = new JButton();
		sellBackButton = new JRadioButton();
		
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		
		refreshListing();
		listScrollPane.setViewportView(shopList);
		
		itemTable.setModel(new DefaultTableModel(new Object[][] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null }, { null, null, null, null } }, new String[] { }));
		tableScrollPane.setViewportView(itemTable);
		
		configurationPanel.setBorder(BorderFactory.createTitledBorder("Configuration"));
		
		shopNameLabel.setText("Shop Name");
		
		identifierLabel.setText("Identifier");
		
		identifierTextField.addActionListener(this::identifierTextFieldActionPerformed);
		
		currencyNameLabel.setText("Currency Name");
		
		saveButton.setText("Save");
		saveButton.addActionListener(this::saveButtonActionPerformed);
		
		sellBackButton.setText("Sell Back Allowed");
		sellBackButton.addActionListener(this::sellBackButtonActionPerformed);
		
		GroupLayout configurationPanelLayout = new GroupLayout(configurationPanel);
		configurationPanel.setLayout(configurationPanelLayout);
		configurationPanelLayout.setHorizontalGroup(configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(configurationPanelLayout.createSequentialGroup().addContainerGap().addGroup(configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(shopNameLabel).addComponent(identifierLabel)).addGap(18, 18, 18).addGroup(configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(identifierTextField).addComponent(shopNameTextField, GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addComponent(currencyNameLabel).addGap(18, 18, 18).addComponent(currencyNameTextField, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE).addGap(35, 35, 35)).addGroup(GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addComponent(sellBackButton).addGap(166, 166, 166)))).addGroup(configurationPanelLayout.createSequentialGroup().addGap(246, 246, 246).addComponent(saveButton, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE).addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		configurationPanelLayout.setVerticalGroup(configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, configurationPanelLayout.createSequentialGroup().addGap(19, 19, 19).addGroup(configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(identifierLabel).addComponent(identifierTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(currencyNameTextField, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE).addComponent(currencyNameLabel)).addGap(18, 18, 18).addGroup(configurationPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(shopNameLabel).addComponent(shopNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(sellBackButton)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(saveButton).addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		
		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(listScrollPane, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE).addGap(0, 0, 0).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(tableScrollPane, GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE).addComponent(configurationPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(listScrollPane).addGroup(layout.createSequentialGroup().addComponent(tableScrollPane, GroupLayout.PREFERRED_SIZE, 383, GroupLayout.PREFERRED_SIZE).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(configurationPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		
		pack();
	}// </editor-fold>
	
	/**
	 * Sll the requirements for this gui to load are initialized in this method
	 */
	private void initializeRequirements() {
		ShopRepository.registerAll();
	}
	
	/**
	 * When an action is performed in the {@link #identifierTextField}, necessary handling is done here
	 */
	private void identifierTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println("evt = [" + evt + "]");
	}
	
	/**
	 * Whenh an action is performed on the {@link #sellBackButton}, necessary handling is done here
	 */
	private void sellBackButtonActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println("evt = [" + evt + "]");
	}
	
	/**
	 * When the sav ebutton invokes and event, it is handled here
	 */
	private void saveButtonActionPerformed(ActionEvent evt) {
		System.out.println("evt = [" + evt + "]");
	}
	
	protected void updateTable(int index) {
		final Shop shop = getShopByIndex(index);
		if (shop == null) {
			throw new IllegalStateException("Unable to find shop by index " + index);
		}
		DefaultTableModel model = new DefaultTableModel() {
			
			@Override
			public boolean isCellEditable(int row, int column) {
				return column != 0;
			}
		};
		model.addColumn("Name");
		model.addColumn("Id");
		model.addColumn("Amount");
		if (shop != null && shop.getItems() != null) {
			for (Item item : shop.getItems()) {
				if (item == null) {
					continue;
				}
				model.addRow(new Object[] { item.getDefinitions().getName(), item.getDefinitions().getId(), item.getAmount() });
			}
		}
		identifierTextField.setText(String.valueOf(shop.getIdentifier()));
		shopNameTextField.setText(shop.getName());
		itemTable.setModel(model);
		setTableModelListener();
		itemTable.scrollRectToVisible(itemTable.getCellRect(itemTable.getRowCount() - 1, itemTable.getColumnCount(), true));
	}
	
	/**
	 * When events are fired on the table this method is invoked
	 */
	private void setTableModelListener() {
		
		itemTable.getModel().addTableModelListener(e -> {
			System.out.println("Event invoked: " + e);
		});
		// TODO
	}
	
	/**
	 * This method refreshes the shops shown on the {@link #shopList}
	 */
	private void refreshListing() {
		shopList.setModel(new AbstractListModel<String>() {
			
			@Override
			public int getSize() {
				return localShops.size();
			}
			
			@Override
			public String getElementAt(int index) {
				Shop shop = getShopByIndex(index);
				if (shop == null) {
					System.out.println("Unable to find shop by index " + index);
					return "N/A";
				}
				return shop.getName();
			}
		});
	}
	
	/**
	 * Gets a sohp by the index, this does not use the identifier value in the map, rather the order in which shops are
	 * stored in the file.
	 */
	private Shop getShopByIndex(int index) {
		int count = 0;
		for (Entry<Integer, Shop> entry : localShops.entrySet()) {
			if (count == index) {
				return entry.getValue();
			}
			count++;
		}
		return null;
	}
	
	/**
	 * @param args
	 * 		the command line arguments
	 */
	public static void main(String... args) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		//</editor-fold>
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			ShopEditor editor = new ShopEditor();
			editor.initializeRequirements();
			editor.setVisible(true);
		});
	}
	// End of variables declaration
}
